export const getTheTeacher = [
  {
    name: "Alex Thompson",
    email: "a.tompson@company.com",
    location: "San Francisco, US",
    status: "Active",
    balance: 1000,
  },
  {
    name: "Sarah Chen",
    email: "sarah.c@company.com",
    location: "Singapore",
    status: "Active",
    balance: 1000,
  },
  {
    name: "James Wilson",
    email: "j.wilson@company.com",
    location: "London, UK",
    status: "Active",
    balance: 1000,
  },
  {
    name: "Maria Garcia",
    email: "m.garcia@company.com",
    location: "Madrid, Spain",
    status: "Active",
    balance: 1000,
  },
  {
    name: "Lars Nielsen",
    email: "l.nielsen@company.com",
    location: "Stockholm, SE",
    status: "Active",
    balance: 1000,
  },
  {
    name: "Eva Kowalski",
    email: "e.kowalski@company.com",
    location: "Seoul, KR",
    status: "Active",
    balance: 1000,
  },
  {
    name: "Emma Laurent",
    email: "e.laurent@company.com",
    location: "Berlin, DE",
    status: "Active",
    balance: 1000,
  },
  {
    name: "Marco Rossi",
    email: "m.rossi@company.com",
    location: "Madrid, Spain",
    status: "Active",
    balance: 1000,
  },
  {
    name: "Yuki Tanaka",
    email: "y.tanaka@company.com",
    location: "Warsaw, PL",
    status: "Active",
    balance: 1000,
  },
  {
    name: "Mike Allison",
    email: "m.allison@company.com",
    location: "San Francisco, US",
    status: "Active",
    balance: 1000,
  },
  {
    name: "John Doe",
    email: "john@example.com",
    location: "USA",
    status: "Active",
    balance: 1000,
  },
];
