export const teachers = [
  { id: '1', name: 'Alex Thompson', email: 'a.tompson@company.com', location: 'San Francisco, US', flag: '🇺🇸' },
  { id: '2', name: 'Sarah Chen', email: 'sarah.c@company.com', location: 'Singapore', flag: '🇸🇬' },
  { id: '3', name: 'James Wilson', email: 'j.wilson@company.com', location: 'London, UK', flag: '🇬🇧' },
  { id: '4', name: 'Maria Garcia', email: 'm.garcia@company.com', location: 'Madrid, Spain', flag: '🇪🇸' },
  { id: '5', name: 'Lars Nielsen', email: 'l.nielsen@company.com', location: 'Stockholm, SE', flag: '🇸🇪' },
  { id: '6', name: 'Eva Kowalski', email: 'e.kowalski@company.com', location: 'Seoul, KR', flag: '🇰🇷' },
  { id: '7', name: 'Emma Laurent', email: 'e.laurent@company.com', location: 'Berlin, DE', flag: '🇩🇪' },
  { id: '8', name: 'Marco Rossi', email: 'm.rossi@company.com', location: 'Madrid, Spain', flag: '🇪🇸' },
  { id: '9', name: 'Yuki Tanaka', email: 'y.tanaka@company.com', location: 'Warsaw, PL', flag: '🇵🇱' },
  { id: '10', name: 'Mike Allison', email: 'm.allison@company.com', location: 'San Francisco, US', flag: '🇺🇸' },
  { id: '11', name: 'Anna Visconti', email: 'anna.visconti@company.com', location: 'Rome, IT', flag: '🇮🇹' },
  { id: '12', name: 'David Kim', email: 'd.kim@company.com', location: 'Paris, FR', flag: '🇫🇷' },
  { id: '13', name: 'Lucia Sorna', email: 'lucia.sorna@company.com', location: 'Copenhagen, DK', flag: '🇩🇰' },
  { id: '14', name: 'Samuel Carteron', email: 'sa.carteron@company.com', location: 'San Francisco, US', flag: '🇺🇸' },
  { id: '15', name: 'Alex Allan', email: 'alex.allan@company.com', location: 'São Paulo, BR', flag: '🇧🇷' },
  { id: '16', name: 'Olivia Brown', email: 'o.brown@company.com', location: 'Sydney, AU', flag: '🇦🇺' },
  { id: '17', name: 'Hiroshi Yamamoto', email: 'h.yamamoto@company.com', location: 'Osaka, JP', flag: '🇯🇵' },
  { id: '18', name: 'Sophie Dubois', email: 's.dubois@company.com', location: 'Montreal, CA', flag: '🇨🇦' },
  { id: '19', name: 'Diego Mendoza', email: 'd.mendoza@company.com', location: 'Mexico City, MX', flag: '🇲🇽' },
  { id: '20', name: 'Lena Müller', email: 'l.mueller@company.com', location: 'Vienna, AT', flag: '🇦🇹' },
  { id: '21', name: 'Raj Patel', email: 'r.patel@company.com', location: 'Mumbai, IN', flag: '🇮🇳' },
  { id: '22', name: 'Astrid Andersen', email: 'a.andersen@company.com', location: 'Oslo, NO', flag: '🇳🇴' },
  { id: '23', name: 'Fatima Al-Sayed', email: 'f.alsayed@company.com', location: 'Cairo, EG', flag: '🇪🇬' },
  { id: '24', name: 'Javier Fernández', email: 'j.fernandez@company.com', location: 'Buenos Aires, AR', flag: '🇦🇷' },
  { id: '25', name: 'Zoe Williams', email: 'z.williams@company.com', location: 'Auckland, NZ', flag: '🇳🇿' },
  { id: '26', name: 'Nikolai Petrov', email: 'n.petrov@company.com', location: 'Moscow, RU', flag: '🇷🇺' },
  { id: '27', name: 'Isabella Rossi', email: 'i.rossi@company.com', location: 'Milan, IT', flag: '🇮🇹' },
  { id: '28', name: 'Cheng Wei', email: 'c.wei@company.com', location: 'Shanghai, CN', flag: '🇨🇳' },
  { id: '29', name: 'Licia Patel', email: 'l.patel@company.com', location: 'Nairobi, KE', flag: '🇰🇪' }
];
